from prompts import Prompt
# Here are to be found methods that do analysis on the results of the Claude-generated answers

def extract_config_from_output(output: str):
    # Find the unified diff in the output
    diff_start = output.find('---')
    diff_end = output.find('+++', diff_start)
    if diff_start == -1 or diff_end == -1:
        raise ValueError("Unified diff not found in the output.")
    diff = output[diff_start:diff_end].splitlines()

    # Parse the unified diff to extract generated config (lines starting with '+')
    generated_config = [line[1:] for line in diff if line.startswith('+')]
    # Want the generated config to be a string, not a list of lines
    return '\n'.join(generated_config) # this will be the generated config as a string, without the '+' signs


# Method to compare the config file generated by Claude with a given one, and return a list of differences
# One of the files will be taken from a unified diff generated by Claude, the other is the original .yml file
def compare_configs(og_filepath: str, prompt: Prompt):
    # Read original file path
    with open(og_filepath, 'r') as f:
        og_config = f.read().splitlines()

    # Get the generated config from the prompt
    generated_config = extract_config_from_output(prompt.getOutput())

    # Compare the two configs line by line and return a list of differences
    differences = []
    for og_line, gen_line in zip(og_config, generated_config.splitlines()):
        if og_line != gen_line:
            differences.append((og_line, gen_line)) # tuple of (original line, generated line)

    return differences
