import subprocess
import shutil
from pathlib import Path
import json

# Global info
jsonl_filename = "../runs_archive.jsonl"
prompt_prefix = """
FILE EDIT POLICY (must follow):
- Do not write, edit, delete, or rename any files.
- If changes are needed, output a unified diff only.
- The diff must include file paths and enough context lines to apply cleanly.
- Do not include any explanation inside the diff block.
- If information is missing to generate a correct diff, ask one concise question.
"""

# Prompt class - this defines an object for the individual prompt
class Prompt:
    # Initialize
    def __init__(self, index: str, query: str, output: str, errlog: str, returncode: int, success: bool):
        self.id = index # unique identifier for this particular prompt
        self.query = query # the query passed into the LLM
        self.output = output # the output generated by the LLM in response to the query
        self.errlog = errlog # the error log generated by the LLM in response to the query
        self.returncode = returncode # the return code of the prompt
        self.success = success # boolean, whether the generated code runs successfully
    
    # truncate the query to show just the beginning, truncate the output, display stats
    def printPrompt(self, q_size: int = 100, o_size: int = 100, e_size: int = 100):
        query_short = (self.query[:q_size] + '..') if len(self.query) > q_size else self.query
        output_short = (self.output[:o_size] + '..') if len(self.output) > o_size else self.output
        error_short = (self.errlog[:e_size] + '..') if len(self.errlog) > e_size else self.errlog
        print("Prompt ID: " + self.id)
        print("Query: " + query_short)
        print("Output log: " + output_short)
        print("Error log: " + error_short)
        print("Success: " + str(self.success))
    
    # returns boolean describing whether the code runs or not
    def getSuccess(self):
        return self.success
        
    # more functions as needed
    
# PromptDict class - this defines a dictionary where each
class PromptDict:
    # initialize with no prompts
    def __init__(self):
        self.prompts = {}
    
    # get current size of the dictionary
    def getSize(self):
        return len(self.prompts)
    
    # add a prompt to the dictionary
    def addPrompt(self, prompt: Prompt):
        size = len(self.prompts)
        self.prompts[size] = prompt
    
    # add a list of prompts to the dictionary
    def addPrompts(self, prompts_list: list):
        size = len(self.prompts)
        for i in range(len(prompts_list)):
            self.prompts[size + i] = prompts_list[i]
    
    # loads list of prompts into the dictionary from a JSONL file
    def loadFromJsonl(self, filepath: str):
        jsonl_path = Path(filepath)

        if not jsonl_path.exists():
            raise FileNotFoundError(f"JSONL file not found: {jsonl_path}")

        self.prompts = {}

        with jsonl_path.open("r", encoding="utf-8") as f:
            for idx, line in enumerate(f):
                line = line.strip()
                if not line:
                    continue

                record = json.loads(line)

                prompt = Prompt(
                    record["id"],
                    record["query"],
                    record["output_log"],
                    record["error_log"],
                    record["returncode"],
                    record["success"],
                )

                self.prompts[idx] = prompt
    
    # Exports current dictionary to a JSONL file
    def exportToJsonl(self, filepath: str):
        jsonl_path = Path(filepath)
        with jsonl_path.open("a", encoding="utf-8") as f:
            for key, value in self.prompts.items():
                record = {
                    "id": value.id,
                    "query": value.query,
                    "output_log": value.output,
                    "error_log": value.errlog,
                    "returncode": value.returncode,
                    "success": value.success,
                }

                f.write(json.dumps(record, ensure_ascii=False))
                f.write("\n")
                f.flush()
        
        
    def printPrompts(self):
        for key, value in self.prompts.items():
            value.printPrompt()
            
    # get a prompt at a specific index
    def getPrompt(self, index: int):
        return self.prompts[index]
    
    # Find a prompt with a specific identifier, return the prompt object if found, else return None
    def findPrompt(self, prompt_id: str):
        for key, value in self.prompts.items():
            if value.id == prompt_id:
                return value
        return None
    
    # move a specific prompt with index i to another index j, shifting all the other prompts without reordering them
    # DO NOT IMPLEMENT FOR NOW
    def relabelIndices(self):
        # implement here
        return 0

            
# METHODS
# MUST be run from Agc_claude directory


# Ask user to type idenitifier and query
def getIDQuery(directory: PromptDict):
    # First ask user if they would like to manally enter prompt or import from a .txt file
    method = input("Would you like to (1) manually enter a query or (2) import a query from a .txt file? (Enter 1 or 2): ")
    if method == "1":
        identifier = input("Enter a unique identifier: ")
        # Add check to see if directory already has this identifier, if yes ask for a different one
        while directory.findPrompt(identifier) is not None:
            print("Identifier already exists in directory. Please enter a different one.")
            identifier = input("Enter a unique identifier: ")
        user_query = input("Enter query for Claude:\n>")
        return identifier, user_query
    elif method == "2":
        filepath = '../queries/' + input("Enter the file path of the .txt file containing the query (relative to queries directory, without .txt): ") + '.txt'
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                user_query = f.read()
            identifier = filepath.split("/")[-1].split(".")[0] # use the filename without .txt and directory name
            return identifier, user_query
        except FileNotFoundError:
            print("File not found.")
            return None, None

# Give the query to Claude and get output and error logs, save as Prompt object
def promptClaude(identifier: str, query: str):
    process = subprocess.run(
        ["claude", "-p", query + "\n" + prompt_prefix],
        capture_output=True,
        text=True
    )
    print("returncode:", process.returncode)
    print("stdout:\n", process.stdout)
    print("stderr:\n", process.stderr)
    
    prompt = Prompt(identifier, query, process.stdout, process.stderr, process.returncode, (process.returncode == 0))
    print("Saved prompt object")
    return prompt

# Extract the unified diff from the output log of a prompt, if it exists, else return None
def extractDiff(prompt: Prompt):
    output = prompt.output
    diff_start = output.find("```diff") # look for the start of the diff block, which should be denoted by ```diff
    if diff_start == -1: # if no diff block is found, return None
        return None
    diff_end = output.find("```", diff_start + 6) # look for the end of the diff block, which should be denoted by ``` and should come after the start of the diff block
    if diff_end == -1: # if no end of diff block is found, meaning the diff block is not closed properly, return None
        return None
    diff = output[diff_start + 7:diff_end].strip() # extract the diff from the output log, removing the ```diff and ``` markers, and stripping any leading or trailing whitespace
    return diff

# Implement the unified diff to the given files, pass it as a prompt to Claude to implement the changes.
# CURRENTLY DOES NOT WORK
def implementDiff(diff: str):
    pre_prompt = """
    The following unified diff describes changes that need to be made to the given file(s).
    Please implement the changes described in the diff.
    You have permission to edit the specified files as needed to implement these changes.  Do not edit any other files. \n
    """
    # Get list of files to be modified
    files_to_modify = set()
    for line in diff.splitlines():
        if line.startswith("+++ ") or line.startswith("--- "):
            filename = line[6:] # get the file path from the diff line, which should come after the "+++ " or "--- " marker and the "a/" or "b/" marker
            filepath = "Claude_Sandbox/" + filename
            files_to_modify.add(filepath)
    # Append list of allowed files to edit to the pre-prompt 
    pre_prompt += "You have permission to edit the following files: " + ", ".join(files_to_modify) + "\n\n"
    # Now pass the pre_prompt and the diff as a prompt to Claude
    full_prompt = pre_prompt + "Here is the unified diff:\n```diff\n" + diff + "\n```\n"
    process = subprocess.run(
        ["claude", "-p", full_prompt],
        capture_output=True,
        text=True
    )
    print("returncode:", process.returncode)
    print("stdout:\n", process.stdout)
    print("stderr:\n", process.stderr)

def displayMainMenu():
    print("Main menu options:")
    print("1. Load new prompt archive")
    print("2. Prompt Claude with query")
    print("3. View all prompts")
    print("4. [PLACEHOLDER] for analysis tools")
    print("5. Export current directory")
    print("6. Print specific prompt")
    print("7. Implement diff from specific prompt")
    print("Press 'q' to quit")
    print("\n")

# Main function, runs at the start of this python script
def main():
    print("Welcome to the Claude controller script.")
    print("Here you can pass a query to prompt Claude, as well as store and analyse the results.")
    print("JSONL Archive file: " + jsonl_filename)
    print("\n")
    
    directory = PromptDict()
    
    displayMainMenu()
    
    entry = input("Select a menu option: ")
    while entry != "q":
        selection = int(entry)
        while selection not in range(1, 10):
            selection = input("Invalid option.  Select again:")
        
        # Load new prompt archive from JSONL file into prompt directorys
        if selection == 1:
            print("WARNING !!  This will overwrite the current prompt directory; exporting it to a JSONL file first is recommended.")
            proceed = input("Are you sure you would like to proceed (y/n)? ")
            if proceed == "y":
                name = input("Which file would you like to import? (Enter filename without .jsonl) ")
                filepath = "../run_archives/" + name + ".jsonl"
                directory.loadFromJsonl(filepath)
                print("Successfully loaded prompts from " + filepath)
        
        # Query Claude and add prompt to directory
        if selection == 2:
            identifier, query = getIDQuery(directory)
            prompt = promptClaude(identifier, query)
            directory.addPrompt(prompt)
            print("Added prompt to directory")
            print("Directory now has " + str(directory.getSize()) + " prompt(s).")
        
        # Print full list of prompts
        if selection == 3:
            directory.printPrompts()
        
        # Export prompt directory to JSONL file
        if selection == 5:
            name = input("Choose name for JSONL file (omit .jsonl in your entry):")
            filename = name + ".jsonl"
            filepath = "../run_archives/" + filename
            # Check if file already exists in run_archives, to avoid overwriting
            directory.exportToJsonl(filepath)
            print("Successfully exported current directory to " + filepath)
        
        # Prints a specific prompt the user specifies
        if selection == 6:
            promptid = input("Enter prompt ID to be printed: ")
            prompt = directory.findPrompt(promptid)
            if prompt is not None:
                prompt.printPrompt(q_size=1000, o_size=1000, e_size=1000)
            else:
                print("Prompt with ID " + promptid + " not found in directory.")

        # Implement diff from a specific prompt, if it exists
        if selection == 7:
            promptid = input("Enter prompt ID to extract diff from and implement: ")
            prompt = directory.findPrompt(promptid)
            if prompt is not None:
                diff = extractDiff(prompt)
                if diff is not None:
                    implementDiff(diff)
                else:
                    print("No unified diff found in output log of prompt with ID " + promptid)
            else:
                print("Prompt with ID " + promptid + " not found in directory.")
        
        # Show main menu again
        displayMainMenu()
        
        entry = input("Select a menu option: ")
    
if __name__ == "__main__":
    main()