import subprocess
import shutil
from pathlib import Path
import json

# Global info
jsonl_filename = "../runs_archive.jsonl"
prompt_prefix = """
FILE EDIT POLICY (must follow):
- Do not write, edit, delete, or rename any files.
- If changes are needed, output a unified diff only.
- The diff must include file paths and enough context lines to apply cleanly.
- Do not include any explanation inside the diff block.
- If information is missing to generate a correct diff, ask one concise question.
"""

# Prompt class - this defines an object for the individual prompt
class Prompt:
    # Initialize
    def __init__(self, index: str, query: str, output: str, errlog: str, returncode: int, success: bool):
        self.id = index # unique identifier for this particular prompt
        self.query = query # the query passed into the LLM
        self.output = output # the output generated by the LLM in response to the query
        self.errlog = errlog # the error log generated by the LLM in response to the query
        self.returncode = returncode # the return code of the prompt
        self.success = success # boolean, whether the generated code runs successfully
    
    # truncate the query to show just the beginning, truncate the output, display stats
    def printPrompt(self, q_size: int = 100, o_size: int = 100, e_size: int = 100):
        query_short = (self.query[:q_size] + '..') if len(self.query) > q_size else self.query
        output_short = (self.output[:o_size] + '..') if len(self.output) > o_size else self.output
        error_short = (self.errlog[:e_size] + '..') if len(self.errlog) > e_size else self.errlog
        print("Prompt ID: " + self.id)
        print("Query: " + query_short)
        print("Output log: " + output_short)
        print("Error log: " + error_short)
        print("Success: " + str(self.success))
    
    # returns boolean describing whether the code runs or not
    def getSuccess(self):
        return self.success
        
    # more functions as needed
    
# PromptDict class - this defines a dictionary where each
class PromptDict:
    # initialize with no prompts
    def __init__(self):
        self.prompts = {}
    
    # get current size of the dictionary
    def getSize(self):
        return len(self.prompts)
    
    # add a prompt to the dictionary
    def addPrompt(self, prompt: Prompt):
        size = len(self.prompts)
        self.prompts[size] = prompt
    
    # add a list of prompts to the dictionary
    def addPrompts(self, prompts_list: list):
        size = len(self.prompts)
        for i in range(len(prompts_list)):
            self.prompts[size + i] = prompts_list[i]
    
    # loads list of prompts into the dictionary from a JSONL file
    def loadFromJsonl(self, filepath: str):
        jsonl_path = Path(filepath)

        if not jsonl_path.exists():
            raise FileNotFoundError(f"JSONL file not found: {jsonl_path}")

        self.prompts = {}

        with jsonl_path.open("r", encoding="utf-8") as f:
            for idx, line in enumerate(f):
                line = line.strip()
                if not line:
                    continue

                record = json.loads(line)

                prompt = Prompt(
                    record["id"],
                    record["query"],
                    record["output_log"],
                    record["error_log"],
                    record["returncode"],
                    record["success"],
                )

                self.prompts[idx] = prompt
    
    # Exports current dictionary to a JSONL file
    def exportToJsonl(self, filepath: str):
        jsonl_path = Path(filepath)
        with jsonl_path.open("a", encoding="utf-8") as f:
            for key, value in self.prompts.items():
                record = {
                    "id": value.id,
                    "query": value.query,
                    "output_log": value.output,
                    "error_log": value.errlog,
                    "returncode": value.returncode,
                    "success": value.success,
                }

                f.write(json.dumps(record, ensure_ascii=False))
                f.write("\n")
                f.flush()
        
        
    def printPrompts(self):
        for key, value in self.prompts.items():
            value.printPrompt()
            
    # get a prompt at a specific index
    def getPrompt(self, index: int):
        return self.prompts[index]
    
    # move a specific prompt with index i to another index j, shifting all the other prompts without reordering them
    def relabelIndices():
        # implement here
        return 0

            
# METHODS
# MUST be run from Agc_claude directory


# Ask user to type idenitifier and query
def getIDQuery(directory: PromptDict):
    identifier = input("Enter a unique identifier: ")
    # Add check to see if directory already has this identifier, if yes ask for a different one
    user_query = input("Enter query for Claude:\n>")
    return identifier, user_query

# Give the query to Claude and get output and error logs, save as Prompt object
def promptClaude(identifier: str, query: str):
    process = subprocess.run(
        ["claude", "-p", query + "\n" + prompt_prefix],
        capture_output=True,
        text=True
    )
    print("returncode:", process.returncode)
    print("stdout:\n", process.stdout)
    print("stderr:\n", process.stderr)
    
    prompt = Prompt(identifier, query, process.stdout, process.stderr, process.returncode, (process.returncode == 0))
    print("Saved prompt object")
    return prompt


# Main function, runs at the start of this python script
def main():
    print("Welcome to the Claude controller script.")
    print("Here you can pass a query to prompt Claude, as well as store and analyse the results.")
    print("JSONL Archive file: " + jsonl_filename)
    print("\n")
    
    directory = PromptDict()
    
    print("Main menu options:")
    print("1. Load new prompt archive")
    print("2. Prompt Claude with query")
    print("3. View all prompts")
    print("4. [PLACEHOLDER] for analysis tools")
    print("5. Export current directory")
    print("Press 'q' to quit")
    print("\n")
    
    entry = input("Select a menu option:")
    while entry != "q":
        selection = int(entry)
        while selection not in range(1, 6):
            selection = input("Invalid option.  Select again:")
        
        # Load new prompt archive from JSONL file into prompt directorys
        if selection == 1:
            print("WARNING !!  This will overwrite the current prompt directory; exporting it to a JSONL file first is recommended.")
            proceed = input("Are you sure you would like to proceed (y/n)? ")
            if proceed == "y":
                name = input("Which file would you like to import? (Enter filename without .jsonl) ")
                filepath = "../run_archives/" + name + ".jsonl"
                directory.loadFromJsonl(filepath)
                print("Successfully loaded prompts from " + filepath)
        
        # Query Claude and add prompt to directory
        if selection == 2:
            identifier, query = getIDQuery(directory)
            prompt = promptClaude(identifier, query)
            directory.addPrompt(prompt)
            print("Added prompt to directory")
            print("Directory now has " + str(directory.getSize()) + " prompt(s).")
        
        # Print full list of prompts
        if selection == 3:
            directory.printPrompts()
        
        # Export prompt directory to JSONL file
        if selection == 5:
            name = input("Choose name for JSONL file (omit .jsonl in your entry):")
            filename = name + ".jsonl"
            filepath = "../run_archives/" + filename
            # Check if file already exists in run_archives, to avoid overwriting
            directory.exportToJsonl(filepath)
            print("Successfully exported current directory to " + filepath)
        
        # Show main menu again
        print("Main menu options:")
        print("1. Load new prompt archive")
        print("2. Prompt Claude with query")
        print("3. View all prompts")
        print("4. [PLACEHOLDER] for analysis tools")
        print("5. Export current directory")
        print("Press 'q' to quit")
        print("\n")
        
        entry = input("Select a menu option:")
    
if __name__ == "__main__":
    main()