import json
from pathlib import Path

# Prompt class - this defines an object for the individual prompt
class Prompt:
    # Initialize
    def __init__(self, index: str, query: str, output: str, errlog: str, returncode: int, success: bool):
        self.id = index # unique identifier for this particular prompt
        self.query = query # the query passed into the LLM
        self.output = output # the output generated by the LLM in response to the query
        self.errlog = errlog # the error log generated by the LLM in response to the query
        self.returncode = returncode # the return code of the prompt
        self.success = success # boolean, whether the generated code runs successfully
    
    # truncate the query to show just the beginning, truncate the output, display stats
    def printPrompt(self, q_size: int = 100, o_size: int = 100, e_size: int = 100):
        query_short = (self.query[:q_size] + '..') if len(self.query) > q_size else self.query
        output_short = (self.output[:o_size] + '..') if len(self.output) > o_size else self.output
        error_short = (self.errlog[:e_size] + '..') if len(self.errlog) > e_size else self.errlog
        print("Prompt ID: " + self.id)
        print("Query: " + query_short)
        print("Output log: " + output_short)
        print("Error log: " + error_short)
        print("Success: " + str(self.success))
    
    # returns boolean describing whether the code runs or not
    def getSuccess(self):
        return self.success
    
    # returns the output log of the prompt (should be a string)
    def getOutput(self):
        return self.output
        
    # more functions as needed
    
# PromptDict class - this defines a dictionary where each
class PromptDict:
    # initialize with no prompts
    def __init__(self):
        self.prompts = {}
    
    # get current size of the dictionary
    def getSize(self):
        return len(self.prompts)
    
    # add a prompt to the dictionary
    def addPrompt(self, prompt: Prompt):
        size = len(self.prompts)
        self.prompts[size] = prompt
    
    # add a list of prompts to the dictionary
    def addPrompts(self, prompts_list: list):
        size = len(self.prompts)
        for i in range(len(prompts_list)):
            self.prompts[size + i] = prompts_list[i]
    
    # loads list of prompts into the dictionary from a JSONL file
    def loadFromJsonl(self, filepath: str):
        jsonl_path = Path(filepath)

        if not jsonl_path.exists():
            raise FileNotFoundError(f"JSONL file not found: {jsonl_path}")

        self.prompts = {}

        with jsonl_path.open("r", encoding="utf-8") as f:
            for idx, line in enumerate(f):
                line = line.strip()
                if not line:
                    continue

                record = json.loads(line)

                prompt = Prompt(
                    record["id"],
                    record["query"],
                    record["output_log"],
                    record["error_log"],
                    record["returncode"],
                    record["success"],
                )

                self.prompts[idx] = prompt
    
    # Exports current dictionary to a JSONL file
    def exportToJsonl(self, filepath: str):
        jsonl_path = Path(filepath)
        with jsonl_path.open("a", encoding="utf-8") as f:
            for key, value in self.prompts.items():
                record = {
                    "id": value.id,
                    "query": value.query,
                    "output_log": value.output,
                    "error_log": value.errlog,
                    "returncode": value.returncode,
                    "success": value.success,
                }

                f.write(json.dumps(record, ensure_ascii=False))
                f.write("\n")
                f.flush()
        
        
    def printPrompts(self):
        for key, value in self.prompts.items():
            value.printPrompt()
            
    # get a prompt at a specific index
    def getPrompt(self, index: int):
        return self.prompts[index]
    
    # Find a prompt with a specific identifier, return the prompt object if found, else return None
    def findPrompt(self, prompt_id: str):
        for key, value in self.prompts.items():
            if value.id == prompt_id:
                return value
        return None
    
    # move a specific prompt with index i to another index j, shifting all the other prompts without reordering them
    # DO NOT IMPLEMENT FOR NOW
    def relabelIndices(self):
        # implement here
        return 0
